### ISSUE TITLE
Prop stripPastedStyles is ignored 

### ISSUE THREAD

**Issue by vaclav-zeman** [jpuri/react-draft-wysiwyg#549]
I have a react-draft-wysiwyg (1.12.0) component that has `stripPastedStyles` prop as true but it seems to be ignored. 

**Test scenario**
insert a text from Word file to the editor

**Probable bug**
It seems like `stripPastedStyles` is ignored when you're passing also `handlePastedText` that returns true (which it does here, for HTML and code block) to the draftjs Editor.

So a **solution that works for me** is basically passing both `handlePastedText={() => false}` and `stripPasedStyles` as props to the react-draft-wysiwyg comp.

**Comment by berkayk** [comment]
Have the same problem. Thanks @vaclav-zeman for the solution.

**Comment by yohcop** [comment]
This "fix/solution" only worked until 1.12.0. In 1.12.1, it doesn't again.

**Comment by DimitrisNL** [comment]
I've encountered this bug too. stripPastedStyles is completely ignored.

**Comment by jpuri** [comment]
The issue has been fixed with version `1.12.5`.

**Comment by zywcode** [comment]
I have been updated to 1.12.5, but it seems like not work. @jpuri

**Comment by zywcode** [comment]
Thanks @vaclav-zeman  for the solution.

**Comment by gjulivan** [comment]
hi @jpuri , i'm currently having the same problem. stripPastedStyles does not work.
are you sure that you are not filtering the Editor props for stripPastedStyles on filterEditorProps function here?

**Comment by sahar922** [comment]
Thanks @vaclav-zeman  for the solution,
@jpuri I'm running on 1.12.5 and it still doesn't work for me...

**Comment by jpuri** [comment]
There was actually a small issue still left in `stripPastedStyles` property, release `1.12.9` has the fix.

**Comment by atlanteh** [comment]
Works for me in 1.12.11. Thx!

**Comment by t880216t** [comment]
it works on 1.12.13，tks.

**Comment by ckybonist** [comment]
Please close it
